CREATE TABLE IF NOT EXISTS event_similarities
(
    similarity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_a       BIGINT                   NOT NULL UNIQUE,
    event_b       BIGINT                   NOT NULL UNIQUE,
    score         DOUBLE PRECISION         NOT NULL,
    timestamp     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ordered_ids CHECK (event_a < event_b)
);

CREATE TABLE IF NOT EXISTS user_actions
(
    action_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT                   NOT NULL UNIQUE,
    event_id    BIGINT                   NOT NULL UNIQUE,
    action_type VARCHAR(20)              NOT NULL,
    weight      DOUBLE PRECISION         NOT NULL,
    timestamp   TIMESTAMP WITH TIME ZONE NOT NULL
);