server:
  port: 0

grpc:
  server:
    port: 0
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: collector

collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    poll.timeout: 500
    producer:
      topic: "stats.user-actions.v1"
      properties:
        key.serializer: "org.apache.kafka.common.serialization.LongSerializer"
        value.serializer: "kafka.serializer.GeneralAvroSerializer"