server:
  port: 0

grpc:
  server:
    port: 0
  client:
    aggregator:
      address: 'discovery:///aggregator'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: aggregator
  kafka:
    bootstrap-servers: "localhost:9092"
    enable.auto.commit: false
    producer:
      topic: "stats.events-similarity.v1"
      properties:
        key.serializer: "org.apache.kafka.common.serialization.LongSerializer"
        value.serializer: "kafka.serializer.GeneralAvroSerializer"
    consumer:
      topic: "stats.user-actions.v1"
      properties:
        client.id: AggregatorClient
        group.id: "aggregator-consumer"
        key.deserializer: "org.apache.kafka.common.serialization.LongDeserializer"
        value.deserializer: "kafka.deserializer.UserActionDeserializer"
    poll.timeout: 1000ms