server:
  port: 0

spring:
  application:
    name: stats-server

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:6541/stats-db
    username: stats
    password: stats
    driverClassName: org.postgresql.Driver

  # JPA (Hibernate)
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  # SQL init (off)
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql